variables:
  environment: dev
  resourcesEnvironment: dev
  deploymentyamlfile: deployment-dev.yml
  keyvault: patients-fe-$(environment)-01
  VITE_BACKEND_URL: https://$(environment).api.metadent.nl/api
  BackendUrl: $(VITE_BACKEND_URL)
  VITE_CLIENT_NAME: "\"Metadent (DEV)\""
  VITE_APP_VERSION: "\"Version $(Build.BuildNumber)\""
  websiteAddress: patients-$(environment).metadent.nl
  websiteAddressHttps: https://patients-$(environment).metadent.nl
  node-client: $(resourcesEnvironment)
  namespace: metadent

