variables:
  environment: local
  resourcesEnvironment: dev
  deploymentyamlfile: deployment.yml
  keyvault: metadent-$(environment)-01
  websiteAddress: $(environment).metadent.nl
  node-client: $(environment)
  namespace: metadent-$(environment)
  VITE_BACKEND_URL: https://backend-dev.metadent.nl/api
  BackendUrl: $(VITE_BACKEND_URL)
