variables:
  environment: ohcp
  resourcesEnvironment: ohcp
  deploymentyamlfile: deployment-dev.yml
  keyvault: ohcp-patients-test-01
  VITE_BACKEND_URL: https://$(environment).api.metadent.nl/api
  BackendUrl: $(VITE_BACKEND_URL)
  websiteAddress: patients.metadent.nl
  websiteAddressHttps: https://patients.metadent.nl
  node-client: $(resourcesEnvironment)
  namespace: metadent

