jobs:
  # - template: runtests.yml
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
      NODE_OPTIONS: "--max-old-space-size=16384"
    steps:
      - checkout: self
        submodules: true

      - bash: |
          npm install

        displayName: npm install

      - task: Npm@1
        displayName: npm custom
        inputs:
          command: custom
          workingDir: .
          verbose: false
          customCommand: run build

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.BinariesDirectory)/Frontend'
        inputs:
          SourceFolder: dist/
          TargetFolder: $(Build.BinariesDirectory)/Frontend
          CleanTargetFolder: true
          OverWrite: true

      - powershell: |
          Copy-Item .env $(Build.BinariesDirectory)/Frontend/.env
          
          Test-Path $(Build.BinariesDirectory)/Frontend/.env
        displayName: 'Copy .env file'

      - task: ArchiveFiles@2
        displayName: 'Archive $(Build.BinariesDirectory)/Frontend'
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/Frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/PatientsPortal.zip'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: drop
