parameters:
  subscription: ""
  environment: ""

jobs:
  - deployment: DeployWebapp
    displayName: Deploy the web app
    pool:
      name: $(adoPool)
    variables:
      - group: acrSettings
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self

            - task: DownloadPipelineArtifact@2
              displayName: Download Pipeline Artifact
              inputs:
                artifactName: drop
                itemPattern: '**/PatientsPortal.zip'

            - task: ExtractFiles@1
              displayName: Extract files
              inputs:
                archiveFilePatterns: '$(System.ArtifactsDirectory)/../PatientsPortal.zip'
                destinationFolder: $(Build.BinariesDirectory)
                overwriteExistingFiles: true

            - task: AzureKeyVault@2
              displayName: Fetch secrets
              inputs:
                azureSubscription: ${{parameters.subscription}}
                keyVaultName: $(keyvault)
                secretsFilter: "*"

            - task: joachimdalen.env-transform.057845f0-8352-446f-a666-cb0e1f1055e3.EnvTransform@0
              displayName: Transform .env variables
              inputs:
                inputFile: $(Build.BinariesDirectory)/.env
                outputFile: $(Build.BinariesDirectory)/.env

            - task: PowerShell@2
              displayName: Replace backend url if found
              inputs:
                targetType: filePath
                filePath: ./pipelines/templates/powershell/replaceUrls.ps1
                arguments: -SiteContentFolder "$(Build.BinariesDirectory)" -BackendUrl $(VITE_BACKEND_URL)

            - task: ArchiveFiles@2
              displayName: Archive $(Build.BinariesDirectory)
              inputs:
                rootFolderOrFile: $(Build.BinariesDirectory)
                includeRootFolder: false
                archiveFile: $(System.ArtifactsDirectory)/Patients-Updated.zip                

            - task: AzureAppServiceManage@0
              displayName: Stop Web App
              inputs:
                azureSubscription: ${{parameters.subscription}}
                Action: Stop Azure App Service
                WebAppName: $(webAppName)

            - task: AzureRmWebAppDeployment@4
              displayName: Deploy
              inputs:
                ConnectionType: AzureRM
                azureSubscription: ${{parameters.subscription}}
                appType: webAppLinux
                WebAppName: $(webAppName)
                packageForLinux: $(System.ArtifactsDirectory)/Patients-Updated.zip               

            - task: AzureAppServiceManage@0
              displayName: Start Web App
              inputs:
                azureSubscription: ${{parameters.subscription}}
                Action: Start Azure App Service
                WebAppName: $(webAppName)
                
  - deployment: ValidateFEBackendUrl
    displayName: Validate the Patients app's backend url
    pool:
      name: $(adoPoolWindows)
    dependsOn: DeployWebapp  
    environment: ${{parameters.environment}}
    workspace:
      clean: all # what to clean up before the job
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self

            - task: infocaster.webapp-warmup.webapp-warmup.Webapp Warmup@1
              displayName: Warmup App Service $(websiteAddressHttps)
              inputs:
                Url: $(websiteAddressHttps)
                RetryCount: 5
                SleepPeriod: 5
                IgnoreSslError: false
                Suffixes: /
              continueOnError: false

            - task: DownloadPipelineArtifact@2
              displayName: Download Pipeline Artifact
              inputs:
                artifactName: drop
                itemPattern: '**/PatientsPortal.zip'

            - task: ExtractFiles@1
              displayName: Extract files
              inputs:
                archiveFilePatterns: '$(System.ArtifactsDirectory)/../PatientsPortal.zip'
                destinationFolder: $(Build.BinariesDirectory)
                overwriteExistingFiles: true

            - task: AzureKeyVault@2
              displayName: Fetch secrets
              inputs:
                azureSubscription: ${{parameters.subscription}}
                keyVaultName: $(keyvault)
                secretsFilter: "*"

            - task: joachimdalen.env-transform.057845f0-8352-446f-a666-cb0e1f1055e3.EnvTransform@0
              displayName: Transform .env variables
              inputs:
                inputFile: $(Build.BinariesDirectory)/.env
                outputFile: $(Build.BinariesDirectory)/.env

            - task: PowerShell@2
              displayName: Replace backend url if found
              inputs:
                targetType: filePath
                filePath: ./pipelines/templates/powershell/replaceUrls.ps1
                arguments: -SiteContentFolder "$(Build.BinariesDirectory)" -BackendUrl $(VITE_BACKEND_URL)

            - task: PowerShell@2
              displayName: Check for expected backend url
              inputs:
                targetType: filePath
                filePath: ./pipelines/templates/powershell/checkBackendUrl.ps1
                arguments: -SiteContentFolder "$(Build.BinariesDirectory)" -FrontendUrl $(websiteAddressHttps) -BackendUrl $(VITE_BACKEND_URL)


