parameters:
  environment: ''
  subscription: ''
  cdnAddress: ''
  locationEnvironments: []

jobs:
- ${{ each item in parameters.locationEnvironments }}:
  - deployment: deploycontainers${{item.location.name}}
    displayName: Deploy ${{item.location.infix}} ${{item.location.name}} 
    pool:
      name: $(adoPool)
    variables:
      - name: location
        value: ${{item.location.name}}
      - name: cdnAddress
        value: ${{parameters.cdnAddress}}
      - template: ../configs/pod-config.yml
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: job-container.yml
            parameters:
              resourcegroup: aks-${{item.location.infix}}-rg
              cluster: aks-${{item.location.infix}}-01
              subscription: ${{parameters.subscription}}

