name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger: 
- main

variables:
  - template: configs/common.yml

stages:
- stage: BuildForDeploy
  dependsOn: []
  displayName: Build
  jobs:
  - job: ChangeBranchName
    displayName: Change branch name
    pool:
      name: $(adoPool)
    steps:
    - powershell: |
          $BuildNumber="$(Build.BuildNumber)";
          $Branch = "$(Build.SourceBranchName)";
          $Configuration = "$(BuildConfiguration)";

            If (-Not ($Branch  -eq 'main'))
            {
              $suffix = $Branch;

              echo "##vso[build.updatebuildnumber]$($BuildNumber)-$($suffix)"
            }
      displayName: build number naming
  - template: templates/build.yml
