name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
  branches:
    include:
      - main
      - feature/*
      - bugfix/*
      - releases/*
      - hotfix/*

variables:
  - template: configs/common.yml

stages:
  - stage: BuildForDeploy
    dependsOn: []
    displayName: Build
    jobs:
      - job: ChangeBranchName
        displayName: Change branch name
        pool:
          name: $(adoPool)
        steps:
          - powershell: |
              $BuildNumber="$(Build.BuildNumber)";
              $Branch = "$(Build.SourceBranchName)";
              $Configuration = "$(BuildConfiguration)";

                If (-Not ($Branch  -eq 'main'))
                {
                  $suffix = $Branch;

                  echo "##vso[build.updatebuildnumber]$($BuildNumber)-$($suffix)"
                }
            displayName: build number naming
      - template: templates/build-docker-push.yml

  - stage: POC
    dependsOn: BuildForDeploy
    variables:
      - template: configs/poc.yml
    jobs:
      - template: templates/jobs-dev.yml
        parameters:
          subscription: ${{variables.subscription}}
          environment: ${{variables.environment}}
          cdnAddress: ${{variables.cdnAddress}}

  - stage: DEMO
    dependsOn: POC
    variables:
      - template: configs/demo.yml
    # condition: or(contains(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), contains(variables['Build.SourceBranch'], 'refs/heads/releases/'))
    jobs:
      - template: templates/jobs-prd.yml
        parameters:
          subscription: ${{variables.subscription}}
          environment: ${{variables.environment}}
          cdnAddress: ${{variables.cdnAddress}}

  - stage: KIESQLEAN
    dependsOn: DEMO
    variables:
      - template: configs/kiesqlean.yml
    # condition: or(contains(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), contains(variables['Build.SourceBranch'], 'refs/heads/releases/'))
    jobs:
      - template: templates/jobs-prd.yml
        parameters:
          subscription: ${{variables.subscription}}
          environment: ${{variables.environment}}
          cdnAddress: ${{variables.cdnAddress}}
